version: '3.1'
services:
  idp:
    image: ynhidp
    container_name: idp_ui
    restart: always
    ports:
      - 8888:8888
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
  redis:
    image: redis
    container_name: reddis_cache
    restart: always
    ports:
      - 6379:6379
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
  auth-svc:
    image: auth-svc
    container_name: idp_svc
    restart: always
    ports:
      - 4000:4000
    volumes:
      - "./data/db:/app/data/db"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - "redis"